spring.application.name=vital-signs-service
server.servlet.context-path=/api/v1

influxdb.url=http://localhost:8086
influxdb.token=super-secret-auth-token-123
influxdb.org=health_monitoring
influxdb.bucket=vital_signs

server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=adminpassword