server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service-route
              uri: lb://patient-service
              predicates:
                - Path=/api/v1/patients/**
            - id: medical-staff-service-route
              uri: lb://medical-staff-service
              predicates:
                - Path=/api/v1/medical-staff/**
            - id: vital-signs-service-route
              uri: lb://vital-signs-service
              predicates:
                - Path=/api/v1/vital-signs/**
            - id: notification-service-route
              uri: lb://notification-service
              predicates:
                - Path=/api/v1/notifications/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/healthmonitor-realm