spring.application.name=auth-service

server.port=8087

keycloak.server-url=http://localhost:9090
keycloak.realm=healthmonitor-realm
keycloak.client-id=auth-service-backend
keycloak.client-secret=Q4T6eRN5lB520VuELv77mJW8BBZbwKVz

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=adminpassword